[package]
name = "brute_point_set"
version = "0.1.0"
authors = ["joshuazlin <joshlin@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.9.0"
